dockerlabs/play-with-docker/Portus/Portus.1/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

dockerlabs/play-with-docker/Portus/Portus.1/app/views/shared/_aside.html.slim
aside
  ul
    li.active
      a[href="#{url_for root_path}"]
        i[class="fa fa-dashboard"]
        | Dashboard
      - if current_page?(url_for root_path) || current_page?(root_path)
        .list-selected
    li.active
      a[href="#{url_for namespaces_path}"]
        i[class="fa fa-ship"]
        | Namespaces
      - if current_page?(url_for namespaces_path)
        .list-selected
    li.active
      a[href="#{url_for teams_path}"]
        i[class="fa fa-users"]
        | Teams
      - if current_page?(url_for teams_path)
        .list-selected
    - if current_user.admin?
      li.active
        a[href="#{url_for controller: 'admin/dashboard', action: 'index'}"]
          i[class="fa fa-cogs"]
          | Admin
        - if current_page?(url_for controller: 'admin/dashboard', action: 'index')
          .list-selected
    li.active
      a[href="http://port.us.org/documentation" target="_blank"]
        i[class="fa fa-life-ring"]
        | Help

dockerlabs/play-with-docker/Portus/Portus.1/app/views/shared/_header.html.slim
.logo-header.col-xs-12
  a[href="#{url_for root_path}"]
    = image_tag 'layout/portus-logo-dashboard.png'
  i#open_main_menu.fa.fa-bars.fa-lg.pull-left.visible-xs

.text-right.user-header
  .search-header.hidden-xs
    .header-search-form
      = form_tag search_index_path, method: 'get', class: 'navbar-form' do
        = search_field_tag 'search', params[:search], class: 'form-control search-field', placeholder: 'Search'
        = hidden_field_tag 'type', 'repositories'
        button[type="submit" class="btn btn-default"]
          i.fa.fa-search
  .button-container
    .username-logout
      .hidden-xs
        = link_to edit_user_registration_path, class: 'btn-inline-header', data: {placement: 'bottom', toggle: 'tooltip'}, title: 'My profile' do
          = user_image_tag(current_user)
          span.username = current_user.display_username
      = link_to destroy_user_session_path, method: :delete, class: 'topbar btn btn-default', id: 'logout', data: {placement: 'bottom', toggle: 'tooltip'}, title: 'Logout' do
        i.fa.fa-sign-out

dockerlabs/play-with-docker/Portus/Portus.1/app/views/shared/_notification.html.slim
div [id="#{float == true ? 'float' : 'fixed'}-alert" class="#{messages && messages.first ? '' : 'collapse'}"]
  .alert.alert-dismissible.fade.in.text-left[class="alert-#{alert == 'alert' ? 'danger' : 'info'} #{float == true ? 'float-alert' : ''}"]
    button.close class="alert-hide" type="button"
      span aria-hidden="true" &times;
      span.sr-only Close
    .alert-message
      .alert-icon.pull-left
        i.fa.fa-3x class=(alert == 'alert' ? 'fa-exclamation-circle' : 'fa-info-circle')
      p
        - if messages.is_a?(String)
          = messages
        - elsif messages.is_a?(Array)
          - if messages.size == 1
            = messages[0]
          - else
            ul
              - messages.each do |c|
                li
                  = c

javascript:
  refreshFloatAlertPosition()

dockerlabs/play-with-docker/Portus/Portus.1/app/views/shared/_notifications.html.slim
- if current_user && !current_page?(url_for new_admin_registry_path) && !Registry.any?
  .alert.alert-danger.fade.in.text-left.alert-dismissible
    button.close data-dismiss="alert" type="button"
      span aria-hidden="true" &times;
      span.sr-only Close
    .alert-message
      .alert-icon.pull-left
        i.fa.fa-exclamation-circle.fa-3x
      p
        | No registry found.
      - if current_user.admin?
        p
          = link_to 'Click here', new_admin_registry_path
          |  to complete configuration.
      - else
        p Ask an administrator to complete configuration.

- flash.each do |key, value|
  - if key == 'notice' || key == 'alert'
    = render template: 'shared/_notification.html.slim',
        locals: { messages: value, alert: key, float: flash[:float] }

= render template: 'shared/_notification.html.slim',
    locals: { messages: nil, alert: 'info', float: true }

dockerlabs/play-with-docker/Portus/Portus.1/app/views/shared/_search.html.slim
.row
  .col-xs-12.visible-xs
    = form_tag search_index_path, method: 'get', class: 'input-group shared-search' do
      .input-group.shared-search
        = search_field_tag 'search', params[:search], class: 'form-control', placeholder: 'Search'
        = hidden_field_tag 'type', 'repositories'
        span.input-group-btn
          button.btn.btn-default
            i.fa.fa-search