dockerlabs/play-with-docker/Portus/config/routes.rb
Rails.application.routes.draw do
  resources :errors, only: [:show]
  resources :teams, only: [:index, :show, :create, :update] do
    member do
      get "typeahead/:query" => "teams#typeahead", :defaults => { format: "json" }
    end
  end
  get "/teams/typeahead/:query" => "teams#all_with_query", :defaults => { format: "json" }

  resources :team_users, only: [:create, :destroy, :update]
  resources :namespaces, only: [:create, :index, :show, :update] do
    put "change_visibility", on: :member
    resources :webhooks do
      resources :headers, only: [:create, :destroy], controller: :webhook_headers
      resources :deliveries, only: [:update], controller: :webhook_deliveries
      member do
        put "toggle_enabled"
      end
    end
  end
  get "namespaces/typeahead/:query" => "namespaces#typeahead", :defaults => { format: "json" }

  resources :repositories, only: [:index, :show, :destroy] do
    post :toggle_star, on: :member
    resources :comments, only: [:create, :destroy]
  end

  resources :tags, only: [:destroy]

  resources :application_tokens, only: [:create, :destroy]

  devise_for :users, controllers: { registrations: "auth/registrations",
                                    sessions:      "auth/sessions",
                                    passwords:     "passwords" }
  resource :dashboard, only: [:index]
  resources :search, only: [:index]

  authenticated :user do
    root "dashboard#index", as: :authenticated_root
  end

  devise_scope :user do
    root to: "auth/sessions#new"
    put "toggle_enabled/:id", to: "auth/registrations#toggle_enabled", as: :toggle_enabled
  end

  namespace :v2, module: "api/v2", defaults: { format: :json } do
    root to: "ping#ping", as: :ping
    resource :token, only: [:show]
    resource :webhooks, only: [] do
      resources :events, only: [:create]
    end
  end

  namespace :admin do
    resources :activities, only: [:index]
    resources :dashboard, only: [:index]
    resources :registries, except: [:show, :destroy]
    resources :namespaces, only: [:index]
    resources :teams, only: [:index]
    resources :users do
      put "toggle_admin", on: :member
    end
  end

  # Error pages.
  %w(401 404 422 500).each do |code|
    get "/#{code}", to: "errors#show", status: code
  end
end

dockerlabs/play-with-docker/Portus/app/models/repository.rb
# == Schema Information
#
# Table name: repositories
#
#  id           :integer          not null, primary key
#  name         :string(255)      default(""), not null
#  namespace_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  marked       :boolean          default("0")
#
# Indexes
#
#  fulltext_index_repositories_on_name          (name)
#  index_repositories_on_name_and_namespace_id  (name,namespace_id) UNIQUE
#  index_repositories_on_namespace_id           (namespace_id)
#

class Repository < ActiveRecord::Base
  include PublicActivity::Common
  include SearchCop

  belongs_to :namespace
  has_many :tags, dependent: :delete_all
  has_many :stars, dependent: :delete_all
  has_many :comments, dependent: :delete_all

  # We don't validate the format because we get that from the registry, and
  # it's guaranteed to be well-formatted there.
  validates :name, presence: true, uniqueness: { scope: "namespace_id" }

  search_scope :search do
    attributes :name
    attributes namespace_name: "namespace.name"

    # TODO: (mssola): we are experiencing some issues with MariaDB's fulltext
    # support. Because of that, the following two options have been disabled
    # until we find a solution for it.
    # options :name, type: :fulltext
    # options :namespace_name, type: :fulltext
  end

  # Returns the full name for this repository. What this means is that it
  # returns the bare name if it belongs to the global namespace, otherwise
  # it prefixes the name with the name of the namespace.
  def full_name
    namespace.global? ? name : "#{namespace.name}/#{name}"
  end

  # Set this repo as starred for the given user if there was no star
  # associated. Otherwise, remove the star.
  def toggle_star(user)
    star = stars.find_by(user: user)
    star ? star.destroy : stars.create(user: user)
  end

  # Check if this repo has been starred by the given user.
  def starred_by?(user)
    stars.exists? user: user
  end

  # Returns an array of all the tags from this repository grouped by the
  # digest.
  def groupped_tags
    tags.group_by(&:digest).values.sort do |x, y|
      y.first.created_at <=> x.first.created_at
    end
  end

  # Updates the activities related to this repository and adds a new activity
  # regarding the removal of this.
  def delete_and_update!(actor)
    logger.tagged("catalog") { logger.info "Removed the image '#{name}'." }

    # Take care of current activities.
    PublicActivity::Activity.where(trackable: self).update_all(
      trackable_type: Namespace,
      trackable_id:   namespace.id,
      recipient_type: nil
    )

    # Add a "delete" activity"
    namespace.create_activity(
      :delete,
      owner:      actor,
      recipient:  self,
      parameters: {
        repository_name: name,
        namespace_id:    namespace.id,
        namespace_name:  namespace.clean_name
      }
    )

    destroy
  end

  # Handle a push event from the registry.
  def self.handle_push_event(event)
    registry = Registry.find_from_event(event)
    return if registry.nil?

    namespace, repo_name, tag_name = registry.get_namespace_from_event(event)
    return if namespace.nil?

    repository = Repository.add_repo(event, namespace, repo_name, tag_name)
    return if repository.nil?

    namespace.repositories << repository if namespace
    repository
  end

  # Handle a delete event.
  def self.handle_delete_event(event)
    registry = Registry.find_from_event(event)
    return if registry.nil?

    # Fetch the repo.
    ns, repo_name, = registry.get_namespace_from_event(event, false)
    repo = ns.repositories.find_by(name: repo_name)
    return if repo.nil? || repo.marked?

    # Destroy tags and the repository if it's empty now.
    user = User.find_from_event(event)
    repo.tags.where(digest: event["target"]["digest"], marked: false).map do |t|
      t.delete_and_update!(user)
    end
    repo = repo.reload
    repo.delete_and_update!(user) if !repo.nil? && repo.tags.empty?
  end

  # Add the repository with the given `repo` name and the given `tag`. The
  # actor is guessed from the given `event`.
  def self.add_repo(event, namespace, repo, tag)
    actor = User.find_from_event(event)
    return if actor.nil?

    # Get or create the repository as "namespace/repo". If both the repo and
    # the given tag already exists, update the digest and return early.
    repository = Repository.find_by(namespace: namespace, name: repo)
    if repository.nil?
      repository = Repository.create(namespace: namespace, name: repo)
    elsif repository.tags.exists?(name: tag)
      # Update digest if the given tag already exists.
      id, digest = Repository.id_and_digest_from_event(event, repository.full_name)
      tag = repository.tags.find_by(name: tag)
      tag.update!(image_id: id, digest: digest, updated_at: Time.current)
      repository.create_activity(:push, owner: actor, recipient: tag)
      return
    end

    # And store the tag and its activity.
    id, digest = Repository.id_and_digest_from_event(event, repository.full_name)
    tag = repository.tags.create(name: tag, author: actor, digest: digest, image_id: id)
    repository.create_activity(:push, owner: actor, recipient: tag)
    repository
  end

  # Fetch the image ID and the manifest digest from the given event.
  def self.id_and_digest_from_event(event, repo)
    digest = event.try(:[], "target").try(:[], "digest")
    id = ""

    unless digest.blank?
      begin
        id, = Registry.get.client.manifest(repo, digest)
      rescue StandardError => e
        logger.warn "Could not fetch manifest for '#{repo}' with digest '#{digest}': " + e.message
      end
    end

    [id, digest]
  end

  # Create or update the given repository in JSON format. The given repository
  # follows the same JSON format as in the one used by the Catalog API.
  # Therefore, it's a hash with two keys:
  #   - name: the name of the repo to be created/updated.
  #   - tags: an array of strings with the actual tags of the repository.
  # This method will transparently create/remove the tags that the given
  # repository is supposed to have.
  #
  # Note that if the repo is said to be contained inside of a namespace that
  # does not really exist, then this method will do nothing.
  #
  # Returns the final repository object.
  def self.create_or_update!(repo)
    # If the namespace does not exist, get out.
    namespace, name = Namespace.get_from_name(repo["name"])
    return if namespace.nil?

    # The portus user is the author for the created tags.
    portus = User.find_by(username: "portus")

    # Add the needed tags.
    repository = Repository.find_or_create_by!(name: name, namespace: namespace)
    tags = repository.tags.pluck(:name)

    to_be_deleted_tags = tags - repo["tags"]

    client = Registry.get.client

    update_tags client, repository, repo["tags"] & tags
    create_tags client, repository, portus, repo["tags"] - tags

    # Finally remove the tags that are left and return the repo.
    repository.tags.where(name: to_be_deleted_tags).find_each { |t| t.delete_and_update!(portus) }
    repository.reload
  end

  # Update digest of already existing tags.
  def self.update_tags(client, repository, tags)
    portus = User.find_by(username: "portus")

    tags.each do |tag|
      # Try to fetch the manifest digest of the tag.
      begin
        _, digest, = client.manifest(repository.full_name, tag)
      rescue StandardError => e
        logger.tagged("catalog") do
          logger.warn "Could not fetch manifest for '#{repository.full_name}' " \
            "with tag '#{tag}': " + e.message
        end
        next
      end

      # Let's update the tag, if it really changed,
      t = repository.tags.find_by(name: tag)
      t.digest = digest
      if t.changed.any?
        t.save!
        repository.create_activity(:push, owner: portus, recipient: t)
      end
    end
  end

  # Create new tags.
  def self.create_tags(client, repository, author, tags)
    portus = User.find_by(username: "portus")

    tags.each do |tag|
      # Try to fetch the manifest digest of the tag.
      begin
        id, digest, = client.manifest(repository.full_name, tag)
      rescue
        id = ""
        digest = ""
      end

      t = Tag.create!(
        name:       tag,
        repository: repository,
        author:     author,
        digest:     digest,
        image_id:   id
      )
      repository.create_activity(:push, owner: portus, recipient: t)
      logger.tagged("catalog") { logger.info "Created the tag '#{tag}'." }
    end
  end
end

dockerlabs/play-with-docker/Portus/app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  include Deletable

  before_action :set_repository, only: [:show, :destroy, :toggle_star]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = policy_scope(Repository).all
    respond_with(@repositories)
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
    authorize @repository
    @tags = @repository.groupped_tags
    @repository_comments = @repository.comments.all
    respond_with(@repository)
  end

  # POST /repositories/toggle_star
  def toggle_star
    @repository.toggle_star current_user
    render template: "repositories/star", locals: { user: current_user }
  end

  # Removes all the tags that belong to this repository, and removes it.
  def destroy
    authorize @repository

    # First of all we mark the repo and the tags, so we don't have concurrency
    # problems when "delete" events come in.
    @repository.tags.update_all(marked: true)
    @repository.update_attributes(marked: true)

    # Remove all tags, effectively removing them from the registry too.
    @repository.groupped_tags.map { |t| t.first.delete_by_digest!(current_user) }

    # Delete this repository if all tags were successfully deleted.
    if @repository.reload.tags.any?
      ts = @repository.tags.pluck(:name).join(", ")
      logger.error "The following tags could not be removed: #{ts}."
      redirect_to repository_path(@repository), alert: "Could not remove all the tags", float: true
    else
      @repository.delete_and_update!(current_user)
      redirect_to namespace_path(@repository.namespace),
        notice: "Repository removed with all its tags", float: true
    end
  end

  protected

  def set_repository
    @repository = Repository.find(params[:id])
  end
end

dockerlabs/play-with-docker/Portus/app/helpers/repositories_helper.rb
# Rendering push activities can be tricky, since tags can come on go, and with
# them, dangling repositories that used to contain them. Because of this, this
# helper renders the proper HTML for push activities, while being safe at it.
module RepositoriesHelper
  include ActivitiesHelper

  # Renders a push activity, that is, a repository/tag has been pushed.
  def render_push_activity(activity)
    render_repo_activity(activity, "pushed")
  end

  # Renders a delete activity, that is, a repository/tag has been deleted.
  def render_delete_activity(activity)
    render_repo_activity(activity, "deleted")
  end

  # Returns true if the user can remove the given repository.
  def can_destroy?(repository)
    APP_CONFIG.enabled?("delete") &&
      RepositoryPolicy.new(current_user, repository).destroy?
  end

  protected

  # General method for rendering an activity regarding repositories.
  def render_repo_activity(activity, action)
    owner = content_tag(:strong, "#{activity_owner(activity)} #{action} ")

    namespace = render_namespace(activity)
    namespace += " / " unless namespace.empty?

    owner + namespace + render_repository(activity)
  end

  # Renders the namespace part of the activity in a safe manner. If the
  # namespace still exists, it will be taken as the target for the created
  # link. Otherwise, it will try to fetch the name of the namespace and put it
  # inside of a <span> element. If this is not possible, then an empty string
  # will be returned.
  def render_namespace(activity)
    tr = activity.trackable

    if tr.nil? || tr.is_a?(Namespace)
      if activity.parameters[:namespace_name].nil?
        ""
      else
        namespace = Namespace.find_by(id: activity.parameters[:namespace_id])
        tag_or_link(namespace, activity.parameters[:namespace_name])
      end
    else
      link_to tr.namespace.clean_name, tr.namespace
    end
  end

  # Returns a link if the namespace is not nil, otherwise just a tag with the
  # given name.
  def tag_or_link(namespace, name)
    namespace.nil? ? content_tag(:span, name) : link_to(name, namespace)
  end

  # Renders the repository part of the activity in a safe manner.
  def render_repository(activity)
    repo, link, tag = get_repo_link_tag(activity)

    if link.nil?
      content_tag(:span, "#{repo}#{tag}")
    else
      link_to "#{repo}#{tag}", link
    end
  end

  # Helper for the render_repository method.
  def get_repo_link_tag(activity)
    tr = activity.trackable

    if tr.nil?
      if repo_name(activity).nil?
        ["a repository", nil, ""]
      else
        repo = repo_name(activity)
        ns   = Namespace.find_by(id: activity.parameters[:namespace_id])
        link = ns.nil? ? nil : namespace_path(ns.id)
        [repo, link, tag_part(activity)]
      end
    else
      name, l = name_and_link(tr, activity)
      [name, l, tag_part(activity)]
    end
  end

  # Renders the tag for the given activity. It will return an empty string if
  # the tag could not be found, otherwise it will return the tag with a ":"
  # prefixed to it.
  def tag_part(activity)
    if activity.recipient.nil?
      if activity.parameters[:tag_name].nil?
        ""
      else
        ":#{activity.parameters[:tag_name]}"
      end
    else
      ":#{activity.recipient.name}"
    end
  end

  # Fetch the name of the repo from the given activity.
  def repo_name(activity)
    activity.parameters[:repo_name] || activity.parameters[:repository_name]
  end

  # Returns the name and the link to the given tr depending on whether it's a
  # Namespace or not.
  def name_and_link(tr, activity)
    tr.is_a?(Namespace) ? [repo_name(activity), nil] : [tr.name, tr]
  end
end

dockerlabs/play-with-docker/Portus/app/views/repositories/index.html.slim
.panel.panel-default
  .panel-heading
    | Repositories
  .panel-body
    .table-responsive
      table.table.table-striped.table-hover
        thead
          tr
            th Namespace
            th Repository
        tbody
          - @repositories.each do |repository|
            tr
              td= link_to repository.namespace.clean_name, repository.namespace
              td= link_to repository.name, repository

dockerlabs/play-with-docker/Portus/app/views/repositories/show.html.slim
.btn-toolbar
  #repo-stars.pull-right
    = link_to toggle_star_repository_path(@repository), method: :post,
      class: 'btn btn-primary btn-xs', remote: true, id: 'toggle_star',
      data: {placement: 'bottom', toggle: 'tooltip'},
      title: (@repository.starred_by?(current_user) ? 'Unstar repository' : 'Star repository')
      do
        - if @repository.starred_by?(current_user)
          i.fa.fa-star
        - else
          i.fa.fa-star-o
        span#star-counter.badge
          = @repository.stars.count
  - if can_destroy?(@repository)
    #remove-repo.pull-right
      button.remove-repo.btn-x.btn-edit-role.btn.btn-link.btn-xs[
        data-placement="left"
        data-toggle="popover"
        data-title="Please confirm"
        data-content="<p>Are you sure you want to remove this \
        image?</p><a class='btn btn-default'>No</a> <a class='btn \
        btn-primary' data-method='delete' \
        href='#{url_for(@repository)}'>Yes</a>"
        data-html="true"
        role="button"
        title="Delete image"]
        .fa.fa-trash.space-xs-sides
        ' Delete image
.panel.panel-default
  .panel-heading
    .row
      .col-xs-6
        h5
          = link_to @repository.namespace.clean_name, @repository.namespace
          | /
          = @repository.name
      .col-xs-6.text-right
        - if can_push?(@repository.namespace)
          .circle-label.permissions-label.circle-label-sm[data-placement="left"
            data-toggle="popover"
            data-container=".panel-heading"
            data-content="You can push images"
            data-original-title="What can I do?"
            tabindex="0" data-html="true"]
              i.fa.fa-arrow-up
              ' Push
        - if can_pull?(@repository.namespace)
          .circle-label.permissions-label.circle-label-sm[data-placement="left"
            data-toggle="popover"
            data-container=".panel-heading"
            data-content="You can pull images"
            data-original-title="What can I do?"
            tabindex="0" data-html="true"]
            i.fa.fa-arrow-down
            ' Pull
        - if owner?(@repository.namespace)
          .circle-label.permissions-label.circle-label-sm[data-placement="left"
            data-toggle="popover"
            data-container=".panel-heading"
            data-content="You are an owner of this repository"
            data-original-title="What's my role?"
            tabindex="0" data-html="true"]
            i.fa.fa-male
            ' Owner
        - elsif contributor?(@repository.namespace)
          .circle-label.permissions-label.circle-label-sm[data-placement="left"
            data-toggle="popover"
            data-container=".panel-heading"
            data-content="You are a contributor in this repository"
            data-original-title="What's my role?"
            tabindex="0" data-html="true"]
            i.fa.fa-exchange
            ' Contr.
        - elsif viewer?(@repository.namespace)
          .circle-label.permissions-label.circle-label-sm[data-placement="left"
            data-toggle="popover"
            data-container=".panel-heading"
            data-content="You are a viewer in this repository"
            data-original-title="What's my role?"
            tabindex="0" data-html="true"]
            i.fa.fa-eye
            ' Viewer


  .panel-body
    .table-responsive.tags
      table.table.table-stripped.table-hover
        col.col-40
        col.col-20
        col.col-15
        col.col-20
        - if can_destroy?(@repository)
          col.col-5
        thead
          tr
            th Tag
            th Author
            th Image
            th Pushed at
            - if APP_CONFIG.enabled?("delete")
              th
        tbody
          - @tags.each do |tag|
            - if tag.first.digest.blank?
              - tag.each do |t|
                tr
                  td
                    .label.label-success
                      = t.name
                  td= tag.first.owner
                  td
                    - if tag.first.image_id.blank?
                      = "-"
                    - else
                      span[title="sha256:#{tag.first.image_id}"]
                        = tag.first.image_id[0, 12]
                  td= tag.first.updated_at
            - else
              tr
                td
                  - tag.each do |t|
                    .label.label-success
                      = t.name
                td= tag.first.owner
                td
                  - if tag.first.image_id.blank?
                    = "-"
                  - else
                    span[title="sha256:#{tag.first.image_id}"]
                      = tag.first.image_id[0, 12]
                td= tag.first.updated_at

                - if can_destroy?(@repository)
                  td
                    button.remove-tag.fa.fa-lg.fa-trash-o.btn-x.btn-edit-role.btn.btn-link[
                      data-placement="left"
                      data-toggle="popover"
                      data-title="Please confirm"
                      data-content="<p>Are you sure you want to remove this \
                      tag?</p><a class='btn btn-default'>No</a> <a class='btn \
                      btn-primary' data-method='delete' \
                      href='#{url_for(tag.first)}'>Yes</a>"
                      data-html="true"
                      role="button"
                      title="Delete tag"]


#write_comment_form.collapse
  = form_for [@repository, @repository.comments.build], remote: true, html: {id: 'new-comment-form', class: 'form-horizontal', role: 'form'} do |f|
    .form-group
      = f.label :comment, {class: 'control-label col-md-2'}
      .col-md-7
        = f.text_area(:body, class: 'form-control fixed-size', required: false, placeholder: "Please write a comment.")
    .form-group
      .col-md-offset-2.col-md-7
        = f.submit('Add', class: 'btn btn-primary')

.panel.panel-default
  .panel-heading.clearfix
    .row
      .col-sm-6
        h5
          span class="number_of_comments badge"
            = @repository.comments.count
          span class="comment_string"
            - if @repository.comments.count == 1
              |  Comment
            - else
              |  Comments
      .col-sm-6.text-right
        a#write_comment_repository_btn.btn.btn-xs.btn-link.js-toggle-button role="button"
          i.fa.fa-comment
          | Write a comment

  #comments.panel-body.panel-no-side-padding
    .container-full
      - if @repository_comments.empty?
        .no-comments-found
          ' Nobody has left a comment yet.
      - else
        - @repository_comments.each do |comment|
          = render(comment)

dockerlabs/play-with-docker/Portus/app/views/repositories/star.js.erb
<% if @repository.errors.any? %>
  $('#float-alert p').html("<%= escape_javascript(@repository.errors.full_messages.join('<br/>')) %>");
  $('#float-alert').fadeIn(setTimeOutAlertDelay());
<% else %>

  var element = $('#toggle_star');

  if (<%= @repository.starred_by?(user) %>) {
    element.attr('data-original-title', 'Unstar repository');
    element.find('.fa').removeClass('fa-star-o');
    element.find('.fa').addClass('fa-star');
  } else {
    element.attr('data-original-title', 'Star repository');
    element.find('.fa').removeClass('fa-star');
    element.find('.fa').addClass('fa-star-o');
  }
  $('#star-counter').text(<%= @repository.stars.count %>);

<% end %>